INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('AREA', '권역코드', 12, NULL, 'Y', '권역코드', '2021-05-14', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('BAY_TYPE', '베이유형', 34, NULL, 'Y', '베이유형', '2021-06-15', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('BUS_DIV', '버스구분', 26, NULL, 'Y', '버스구분', '2021-06-07', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('BUS_STS', '버스상태', 72, NULL, 'Y', '버스상태', '2021-09-29', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('CATEGORY', '범례표출위치', 52, NULL, 'Y', '범례표출위치', '2021-07-26', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('CHG_APPR_DIV', '변경승인구분', 4, NULL, 'Y', '변경승인구분', '2021-04-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('CHG_OPER_DIV', '변경운행구분', 3, NULL, 'Y', '변경운행구분', '2021-04-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('COMMON_SENTENCE', '기본문구', 60, NULL, 'Y', '기본문구', '2021-08-03', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('COND_ERROR', '정류소 고장여부', 74, NULL, 'Y', '정류소 고장여부', '2021-09-30', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('COR_TYPE', '코스유형', 69, NULL, 'Y', '코스유형', '2021-09-14', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('CPLNT_TYPE', '민원유형', 6, NULL, 'Y', '민원유형', '2021-04-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('CRS_KIND', '교차로종류', 40, NULL, 'Y', '교차로종류', '2021-07-05', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('CRS_STS', '교차로상태', 71, NULL, 'Y', '교차로상태', '2021-09-29', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('CTR_STS', '제어기상태', 77, NULL, 'Y', '제어기상태', '2021-10-08', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('DAY_DIV', '요일구분', 1, NULL, 'Y', '요일구분', '2021-04-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('DISPATCH_DIV', '디스패치구분', 75, NULL, 'Y', '디스패치구분', '2021-09-30', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('DISPATCH_KIND', '디스패치종류', 76, NULL, 'Y', '디스패치레벨', '2021-09-30', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('DVC_COND', '장치상태', 50, NULL, 'Y', '장치상태', '2021-07-20', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('DVC_KIND', '장치종류', 43, NULL, 'Y', '장치종류', '2021-07-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('EFFECT_TYPE', '행선지안내기 효과 타입', 67, NULL, 'Y', '행선지안내기 효과 타입', '2021-08-26', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('EPLY_YN', '재직여부', 27, NULL, 'Y', '재직여부', '2021-06-07', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('FCLT_COND', '시설상태', 68, NULL, 'Y', '시설상태', '2021-09-06', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('FCLT_KIND', '시설종류', 45, NULL, 'Y', '시설종류', '2021-07-13', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('FILE_TYPE', '파일유형', 42, NULL, 'Y', '파일유형', '2021-07-08', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('FONT', '폰트종류', 54, NULL, 'Y', '폰트종류', '2021-07-26', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('FRAME', '프레임표출모양', 53, NULL, 'Y', '프레임표출모양', '2021-07-26', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('INCDNT_RES_TYPE', '돌발대응유형', 63, NULL, 'Y', '돌발대응유형', '2021-08-11', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('INCDNT_TYPE', '돌발유형', 62, NULL, 'Y', '돌발유형', '2021-08-10', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('INNER_LED', '실내LED코드', 55, NULL, 'Y', '실내LED코드', '2021-07-27', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('INST_LOC', '설치위치', 44, NULL, 'Y', '설치위치', '2021-07-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('INTG_STS', '외부연계상태', 18, NULL, 'Y', '외부연계상태', '2021-05-24', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('INTG_TYPE', '외부연계타입', 14, NULL, 'Y', '외부연계타입', '2021-05-24', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('INTG_URL', '연계URL', 1, NULL, 'Y', '연계URL', '2021-07-15', 'system', 'Y');

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('JIT_DSPCH_YN', '공동배차여부', 29, NULL, 'Y', '공동배차여부', NULL, NULL, NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('JUDG_TYPE', '조치유형', 64, NULL, 'Y', '조치유형', '2021-08-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('KEY_API', 'API 키 저장소', 2, NULL, 'Y', 'API 키 저장소', '2021-07-15', 'system', 'Y');

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('LINK_SET', '기상/대기/뉴스연계 설정', 15, NULL, 'Y', '기상/대기/뉴스연계 설정', '2021-05-24', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('LOC_STOP_DIV', '정차위치구분', 7, NULL, 'Y', '정차위치구분', '2021-04-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('LOGIN_STS', '발생유형', 47, NULL, 'Y', '발생유형', '2021-07-19', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('MOCK_NODE_TYPE', '표준노드유형', 48, NULL, 'Y', '표준노드유형', '2021-07-20', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('MORN_STD', '집중모니터링기준', 38, NULL, 'Y', '집중모니터링기준', '2021-06-28', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('NODE_TYPE', '노드유형', 32, NULL, 'Y', '노드유형', '2021-06-10', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('OPER_APPR_DIV', '운행승인구분', 66, NULL, 'Y', '운행승인구분', '2021-08-19', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('OPER_APPR_STS', '운행승인상태', 65, NULL, 'Y', '운행승인상태', '2021-08-19', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('OPER_EVT_TYPE', '운행이벤트유형', 58, NULL, 'Y', '운행이벤트', '2021-07-30', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('OPER_STS', '운행상태', 73, NULL, 'Y', '운행상태', '2021-09-29', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('ORG_DIV', '기관구분', 9, NULL, 'Y', '기관구분', NULL, NULL, NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('OWNER_TYPE', '소유형태', 16, NULL, 'Y', '소유형태', '2021-05-24', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('PROCE_RST', '처리결과', 46, NULL, 'Y', '처리결과', '2021-07-15', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('PROG_GRP_CD', '프로그램그룹코드', 8, NULL, 'Y', '프로그램그룹코드', '2021-04-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('ROUT_DIV', '노선구분', 22, NULL, 'Y', '노선구분', '2021-06-03', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('ROUT_FTP', '노선생성시문구', 70, NULL, 'Y', '', '2021-09-28', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('ROUT_TYPE', '노선유형', 28, NULL, 'Y', '노선유형', NULL, NULL, NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('RSV_TABLE', '예약결과 테이블 코드', 51, NULL, 'Y', '예약결과 테이블명', '2021-07-23', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('SHAPE_DIV', '노선도모양구분', 31, NULL, 'Y', '노선도모양구분', NULL, NULL, NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('SIG_CTR_TYPE', '신호제어기 유형', 41, NULL, 'Y', '신호제어기 유형', '2021-07-05', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('SKY_COND', '하늘상태', 13, NULL, 'Y', '하늘상태', '2021-05-21', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('STTN_FCLT_TYPE', '정류소시설유형', 33, NULL, 'Y', '정류소시설유형', '2021-06-15', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('SYSTEM_BIT', '시스템비트', 10, NULL, 'Y', '시스템비트', NULL, NULL, NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('SYS_INFO', '기준정보', 35, NULL, 'Y', '기준정보', '2021-06-16', 'system', 'Y');

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('TEST_CODE', '테스트코드', 999, NULL, 'Y', '테스트코드', '2021-10-06', 'system', 'Y');

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('TEST_CODE2', 'TESTcode', 112, NULL, 'Y', 'TEst code 테스트 코드 01', '2021-10-06', 'system', 'Y');

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('TRNS_DIV', '환승구분', 39, NULL, 'Y', '환승구분', '2021-07-01', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('TXT_CD', '텍스트 타입 코드', 59, NULL, 'Y', '텍스트 타입 코드', '2021-08-02', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('VHC_DOOR_DIR_TYPE', '버스문열림방향', 19, NULL, 'Y', '버스문열림방향', '2021-05-28', NULL, NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('VHC_FUEL', '차량연료', 24, NULL, 'Y', '차량연료', '2021-06-03', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('VHC_JAM', '차량혼잡도', 37, NULL, 'Y', '차량혼잡도', '2021-06-16', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('VHC_KIND', '차량종류', 21, NULL, 'Y', '차량종류', '2021-06-02', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('VHC_STS', '버스상태', 25, NULL, 'Y', '버스상태', '2021-06-03', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('VHC_TYPE', '차량유형', 23, NULL, 'Y', '차량유형', '2021-06-03', 'system', 'Y');

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('VIOLT_TYPE', '위반유형', 5, NULL, 'Y', '위반유형', '2021-04-12', 'system', 'Y');

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('VIO_INFO', '위반정보', 36, NULL, 'Y', '위반정보', '2021-06-16', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('VOC_DIV', '음성유형', 56, NULL, 'Y', '음성유형', '2021-07-30', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('WAY_DIV', '상하행구분', 2, NULL, 'Y', '상하행구분', '2021-04-12', 'system', NULL);

INSERT INTO sbrt.BMS_CO_CD_INFO
  (CO_CD, CO_CD_NM, SORT, CO_CD_ENM, USE_YN, REMARK, UPD_DTM, UPD_ID, SYSTEM_YN)
VALUES
  ('WORK_TYPE', '작업유형', 49, NULL, 'Y', '작업유형', '2021-07-20', 'system', NULL);

