INSERT INTO sbrt.BMS_SYSTEM_MST
  (SYSTEM_CD, SYSTEM_VALUE, SYSTEM_NM, UPD_DTM, UPD_ID)
VALUES
  ('SYSTEM_BIT', '1', '烹钦款康包府', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_SYSTEM_MST
  (SYSTEM_CD, SYSTEM_VALUE, SYSTEM_NM, UPD_DTM, UPD_ID)
VALUES
  ('SYSTEM_BIT', '2', '瞒樊款青包府', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_SYSTEM_MST
  (SYSTEM_CD, SYSTEM_VALUE, SYSTEM_NM, UPD_DTM, UPD_ID)
VALUES
  ('SYSTEM_BIT', '3', '傈眉', '2021-04-12', 'system');

