INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0101', '주요 경유지 관리', 'AL', '/ui/BRT/AL0101/AL0101M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-10', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0102', '휴일 관리', 'AL', '/ui/BRT/AL0102/AL0102M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-09', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0103', '코스 관리', 'AL', '/ui/BRT/AL0103/AL0103M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-11', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0104', '노선별 차량 관리', 'AL', '/ui/BRT/AL0104/AL0104M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-13', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0201', '대표노선 운행계획', 'AL', '/ui/BRT/AL0201/AL0201M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-24', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0202', '운행계획 관리(배차 편성)', 'AL', '/ui/BRT/AL0202/AL0202M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-09-30', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0203', '운행계획 관리(정류소)', 'AL', '/ui/BRT/AL0203/AL0203M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-09-30', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0204', '운행계획 주별 조회', 'AL', '/ui/BRT/AL0204/AL0204M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-21', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0301', '배차계획 관리', 'AL', '/ui/BRT/AL0301/AL0301M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-21', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0302', '차량배차 관리', 'AL', '/ui/BRT/AL0302/AL0302M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-09-27', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0303', '대체차량 운행조회', 'AL', '/ui/BRT/AL0303/AL0303M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-09', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0304', '배차계획 관리 그리드', 'AL', '/ui/BRT/AL0304/AL0304M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-25', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('AL0600', '운행결과비교', 'AL', '/ui/BRT/AL0600/AL0600M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-07', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('BM005M01', '릴리즈관리', NULL, '/ui/BM/BM005M01.xml', '_self', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('BM006M01', '단축키관리', NULL, '/cm/common/settingShortCut.xml', '_self', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('FM0100', '시설물 정보 관리', 'FM', '/ui/BMS/FM0100/FM0100M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-20', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('FM0201', '시설물상태 모니터링', 'FM', '/ui/BMS/FM0201/FM0201M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-09-02', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('FM0203', '시설물 업데이트', 'FM', '/ui/BMS/FM0203/FM0203M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-27', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('FM0300', '시설물유지보수관리', 'FM', '/ui/BMS/FM0300/FM0300M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-26', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('MO0101', '실시간 위치정보 모니터링', 'MO', '/ui/BRT/MO0101/MO0101M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-09-13', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('MO0203', '정류소정보모니터링', 'MO', '/ui/BRT/MO0203/MO0203M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-09-08', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('MO0301', '돌발대응시나리오 관리', 'MO', '/ui/BRT/MO0301/MO0301M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-11', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('MO0302', '돌발상황대응이력조회', 'MO', '/ui/BRT/MO0302/MO0302M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-11', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('MO0401', '운행 지시 메시지 관리', 'MO', '/ui/BRT/MO0401/MO0401M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-11', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('MO0500', '전용도로 운행 인가 관리', 'MO', '/ui/BRT/MO0500/MO0500M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-19', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('MO0600', '돌발 모니터링', 'MO', '/ui/BRT/MO0600/MO0600M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-25', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('MO0700', '위반 모니터링', 'MO', '/ui/BRT/MO0700/MO0700M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-25', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0100', '공지관리', 'PI', '/ui/BMS/PI0100/PI0100M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-05-24', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0201', '정류장안내(음성, LED) 관리', 'PI', '/ui/BMS/PI0201/PI0201M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-30', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0202', '음성 편성 관리', 'PI', '/ui/BMS/PI0202/PI0202M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-19', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0203', '기타음성 관리', 'PI', '/ui/BMS/PI0203/PI0203M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-30', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0204', '선택 음성 관리', 'PI', '/ui/BMS/PI0204/PI0204M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-28', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0205', '노선선택별 음성 관리', 'PI', '/ui/BMS/PI0205/PI0205M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-03', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0206', '음성예약관리', 'PI', '/ui/BMS/PI0206/PI0206M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-04', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0207', '음성 편성 정보', 'PI', '/ui/BMS/PI0207/PI0207M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-19', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0301', '뉴스설정', 'PI', '/ui/BMS/PI0301/PI0301M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0302', '뉴스관리', 'PI', '/ui/BMS/PI0302/PI0302M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0303', '사용자 뉴스 관리', 'PI', '/ui/BMS/PI0303/PI0303M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-08', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0400', '기상관리', 'PI', '/ui/BMS/PI0400/PI0400M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0501', '안내기영상 관리', 'PI', '/ui/BMS/PI0501/PI0501M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-07', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0502', '안내기영상 편성', 'PI', '/ui/BMS/PI0502/PI0502M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-08', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0503', '안내기영상 편성 예약', 'PI', '/ui/BMS/PI0503/PI0503M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0601', 'BIT용 컨텐츠 관리', 'PI', '/ui/BMS/PI0601/PI0601M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0602', 'BIT용 컨텐츠 편성', 'PI', '/ui/BMS/PI0602/PI0602M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0603', 'BIT용 컨텐츠 예약', 'PI', '/ui/BMS/PI0603/PI0603M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0701', '행선지안내기용 컨텐츠관리', 'PI', '/ui/BMS/PI0701/PI0701M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-14', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0702', '행선지안내기용 컨텐츠예약', 'PI', '/ui/BMS/PI0702/PI0702M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-14', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0801', '노선안내기용 컨텐츠 관리', 'PI', '/ui/BMS/PI0801/PI0801M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-22', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0901', '전자노선도 화면설정 관리', 'PI', '/ui/BMS/PI0901/PI0901M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-26', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PI0902', '전자노선도 화면설정 예약', 'PI', '/ui/BMS/PI0902/PI0902M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-26', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PR00000001', '기준정보 관리', NULL, NULL, NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '기준정보 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PR00000004', '차량 관리', NULL, '/ui/BMS/PR00000004.xml', '_self', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '차량 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PR00000005', '운전자 관리', NULL, '/ui/BMS/PR00000005.xml', '_self', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '운전자 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PR00000006', '노선 관리', NULL, NULL, NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '노선 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PR00000007', '노선 기초정보 관리', NULL, '/ui/BMS/PR00000007.xml', '_self', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '노선 기초정보 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PR00000008', '노선 경로정보 관리', NULL, '/ui/BMS/PR00000008.xml', '_self', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '노선 경로정보 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PR00000009', '정류소 관리', NULL, NULL, NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '정류소 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PR00000010', '정류소 기초정보 관리', NULL, '/ui/BMS/PR00000010.xml', '_self', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '정류소 기초정보 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('PR00000011', '정류소 환승정보 관리', NULL, '/ui/BMS/PR00000011.xml', '_self', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '정류소 환승정보 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0101', '차고지 관리', 'SI', '/ui/BMS/SI0101/SI0101M01.xml', '_self', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '차고지 관리입니다.', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0102', '운수사 정보 관리', 'SI', '/ui/BMS/SI0102/SI0102M01.xml', NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, NULL);

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0200', '차량 관리', 'SI', '/ui/BMS/SI0200/SI0200M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0300', '운전자 관리', 'SI', '/ui/BMS/SI0300/SI0300M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0401', '노선 기초정보 관리', 'SI', '/ui/BMS/SI0401/SI0401M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-08', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0402', '노선 경로정보 관리', 'SI', '/ui/BMS/SI0402/SI0402M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-14', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0403', '노선 집중모니터링 관리', 'SI', '/ui/BMS/SI0403/SI0403M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-28', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0404', '노선 경로연계 관리', 'SI', '/ui/BMS/SI0404/SI0404M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0405', '대표노선 관리', 'SI', '/ui/BMS/SI0405/SI0405M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-25', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0501', '정류소 기초정보 관리', 'SI', '/ui/BMS/SI0501/SI0501M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-15', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0502', '정류소 환승정보 관리', 'SI', '/ui/BMS/SI0502/SI0502M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-18', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0503', '교차로 기초정보 관리', 'SI', '/ui/BMS/SI0503/SI0503M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-02', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0600', '비상 연락망 관리', 'SI', '/ui/BMS/SI0600/SI0600M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-05', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0701', '운영기준 관리', 'SI', '/ui/BMS/SI0701/SI0701M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-07', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SI0702', '담당자 관리', 'SI', '/ui/BMS/SI0702/SI0702M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-26', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SM0100', '코드관리', 'SM', '/ui/CM/SM0100/SM0100M01.xml', '_self', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SM0110', '코드관리_기존', 'SM', '/ui/CM/SM0100/SM0110M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-05-31', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SM0200', '메뉴관리', 'SM', '/ui/CM/SM0200/SM0200M01.xml', '_self', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SM0300', '프로그램관리', 'SM', '/ui/CM/SM0300/SM0300M01.xml', '_self', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SM0401', '사용자정보관리', 'SM', '/ui/CM/SM0401/SM0401M01.xml', NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, NULL);

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SM0402', '권한관리', 'SM', '/ui/CM/SM0402/SM0402M01.xml', '_self', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SM0403', '로그인이력 조회', 'SM', '/ui/CM/SM0403/SM0403M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-19', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SM0500', '기관관리', 'SM', '/ui/CM/SM0500/SM0500M01.xml', NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, NULL);

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SM0600', '메일관리', 'SM', '/ui/BMS/SM0601/SM0601M01.xml', NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-05-14', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('SP0000', '버튼 전체 샘플', 'SI', '/ui/BMS/SP0000/SP0000M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-19', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('ST0200', '노선별 운행 평균 속도 비교', 'ST', '/ui/BRT/ST0200/ST0200M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-22', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('ST0201', '노선별 정류장 평균 속도 비교', 'ST', '/ui/BRT/ST0201/ST0201M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-26', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('ST0202', '운행 순번 평균 속도 비교 ', 'ST', '/ui/BRT/ST0202/ST0202M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-28', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('ST0203', '운행 배차 평균 속도 비교', 'ST', '/ui/BRT/ST0203/ST0203M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-28', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('ST0301', '돌발 노선별 통계', 'ST', '/ui/BRT/ST0301/ST0301M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-28', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('ST0302', '돌발 날짜별 통계', 'ST', '/ui/BRT/ST0302/ST0302M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-28', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('TEST00', '용덕 테스트 ', 'SI', '/ui/BMS/TEST00/TEST00M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-09-14', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('TEST01', '상민 테스트', 'SI', '/ui/BMS/TEST01/TEST01M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-09-14', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('TM0001', '사용자 찾기 팝업', '', '/ui/TEMP/findUserTemplate.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-05-20', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VD0100', '차내장치 정보 관리', 'VD', '/ui/BMS/VD0100/VD0100M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-15', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VD0201', '차내장치 모니터링', 'VD', '/ui/BMS/VD0201/VD0201M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-06-01', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VD0203', '차내장치 업데이트', 'VD', '/ui/BMS/VD0203/VD0203M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-20', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VD0300', '차내장치 유지보수 관리', 'VD', '/ui/BMS/VD0300/VD0300M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-07-20', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VH0100', 'Dispatch 전송 이력 조회', 'VH', '/ui/BRT/VH0100/VH0100M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-15', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VH0200', '변경운행 이력 조회', 'VH', '/ui/BRT/VH0200/VH0200M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-19', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VH0300', '정위치정차정보 조회', 'VH', '/ui/BRT/VH0300/VH0300M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-17', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VH0400', '이벤트 이력 조회', 'VH', '/ui/BRT/VH0400/VH0400M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-20', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VI0100', '위반 이력 관리', 'VI', '/ui/BRT/VI0100/VI0100M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VI0200', '민원 관리', 'VI', '/ui/BRT/VI0200/VI0200M01.xml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-08-12', 'system');

INSERT INTO sbrt.BMS_PROG_MST
  (PROG_CD, PROG_NM, PROG_GRP_CD, PROG_PH, TARGET, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, HELP_AH, SWP_AH, USE_YN, REMARK, UPD_DTM, UPD_ID)
VALUES
  ('VI2331', '테스트', 'PI', '/바위/주먹/가위', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, '2021-10-18', 'system');

