INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', '', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', '1111111', 'Y', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0101', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-20', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0102', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-09', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0103', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-11', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0104', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-13', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0201', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', NULL, NULL, NULL, '', 'Y', '', '', '', '', '', '2021-09-16', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0202', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-30', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0203', 'Y', 'Y', 'Y', 'N', 'N', 'Y', NULL, NULL, NULL, 'Y', '', '', '', '', 'N', '', '2021-10-20', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0204', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-21', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0301', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', 'Y', '', '', '', '', '', '2021-06-24', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0302', 'Y', 'Y', 'Y', 'N', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-27', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0303', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-09', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0304', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-25', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'AL0600', 'Y', 'Y', 'N', 'N', 'N', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-07', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'BM005M01', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'BM006M01', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'FM0100', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-20', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'FM0201', 'Y', 'Y', 'N', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'FM0203', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, 'Y', '', '', '', '', '', '', '2021-08-27', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'FM0300', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-26', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'M00101', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-13', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'MO0101', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-13', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'MO0203', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-08', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'MO0301', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-11', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'MO0302', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-11', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'MO0401', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-11', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'MO0500', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'MO0600', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-25', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'MO0700', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-25', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0100', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0201', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0202', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0203', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-30', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0204', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0205', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0206', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, 'Y', '', '', '', '', '', '', '2021-08-05', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0207', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-06', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0301', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0302', 'Y', 'Y', 'N', '', '', 'N', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0303', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-08', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0400', 'Y', 'Y', 'N', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-10', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0501', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-07', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0502', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-08', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0503', 'Y', 'Y', 'N', '', '', '', NULL, NULL, NULL, 'Y', '', '', '', '', '', '', '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0601', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0602', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0603', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, 'Y', '', '', '', '', '', '', '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0701', 'Y', 'Y', 'N', '', '', '', NULL, NULL, NULL, '', '', '', 'Y', '', '', '', '2021-08-27', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0702', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, 'Y', '', '', '', '', '', '', '2021-07-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0801', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', 'N', '', '', '', '2021-07-23', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0901', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-26', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PI0902', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, 'Y', '', '', '', '', '', '', '2021-07-26', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PM0001', 'Y', 'Y', 'Y', 'N', 'N', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-20', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000001', NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000002', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000004', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000005', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000006', NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000007', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000008', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000009', NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000010', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'PR00000011', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0101', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', NULL, NULL, NULL, 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0102', 'Y', 'Y', 'Y', NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0200', 'Y', 'Y', 'Y', 'N', 'N', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0300', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0401', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-08', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0402', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', NULL, NULL, NULL, '', 'N', '', '', 'N', '', '', '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0403', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0404', 'Y', 'Y', 'Y', 'N', 'N', 'N', NULL, NULL, NULL, '', 'N', '', '', '', '', '', '2021-07-13', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0405', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-25', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0501', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-15', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0502', 'Y', 'Y', 'Y', 'N', '', 'N', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-01', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0503', 'Y', 'Y', 'Y', 'N', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0600', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-05', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0701', 'Y', 'Y', 'Y', 'N', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-07', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SI0702', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-26', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SM0100', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SM0110', 'Y', 'Y', 'Y', 'N', 'N', 'N', NULL, NULL, NULL, 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SM0200', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SM0300', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SM0401', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SM0402', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SM0403', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-19', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SM0500', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-15', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SM0600', 'Y', 'Y', 'Y', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-05-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'SP0000', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', NULL, NULL, NULL, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', '2021-07-19', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'ST0200', 'Y', 'Y', '', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-25', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'ST0201', 'Y', 'Y', '', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-26', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'ST0202', 'Y', 'Y', '', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'ST0203', 'Y', 'Y', '', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'ST0301', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-26', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'ST0302', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'test', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'TEST00', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'TEST01', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'TM0001', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-21', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VD0100', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-15', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VD0201', 'Y', 'Y', 'N', '', '', 'N', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-01', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VD0203', 'Y', 'Y', 'N', '', '', '', NULL, NULL, NULL, 'Y', 'N', '', '', '', '', '', '2021-07-23', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VD0300', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-07-20', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VH0100', 'Y', 'Y', '', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-27', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VH0200', 'Y', 'Y', '', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-27', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VH0300', 'Y', 'Y', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-17', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VH0400', 'Y', 'Y', '', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-10-27', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VI0100', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000001', 'VI0200', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', '', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', '1111111', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'AL0301', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-21', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'BM005M01', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'BM006M01', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PI0100', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PI0201', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PI0202', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PI0301', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PI0302', 'Y', 'Y', 'N', '', '', 'N', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PI0400', 'Y', 'Y', 'N', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-10', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000001', NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000002', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000003', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000004', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000005', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000006', NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000007', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000008', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000009', NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000010', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'PR00000011', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SI0101', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2021-05-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SI0102', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-24', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SI0200', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SI0300', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SI0401', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-08', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SI0402', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SI0405', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-25', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SI0501', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-15', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SI0502', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-18', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SM0100', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SM0110', 'Y', 'Y', 'Y', 'N', 'N', 'N', NULL, NULL, NULL, 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SM0200', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SM0300', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SM0401', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SM0402', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SM0500', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-15', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'SM0600', 'Y', 'Y', 'Y', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-05-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'teste2', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000002', 'VD0201', 'Y', 'Y', 'N', '', '', 'N', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-01', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', '', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', '1111111', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'AL0301', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-21', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'BM005M01', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'BM006M01', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PI0100', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PI0201', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PI0202', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-08-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PI0301', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-28', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PI0302', 'Y', 'Y', 'N', '', '', 'N', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-03', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PI0400', 'Y', 'Y', 'N', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-10', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000001', NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000002', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000003', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000004', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000005', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000006', NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000007', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000008', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000009', NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000010', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'PR00000011', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SI0101', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2021-05-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SI0102', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-05-24', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SI0200', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SI0300', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SI0401', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-08', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SI0402', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SI0501', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-15', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SI0502', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-18', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SM0100', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SM0110', 'Y', 'Y', 'Y', 'N', 'N', 'N', NULL, NULL, NULL, 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SM0200', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SM0300', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SM0401', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-04', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SM0402', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '2021-04-12', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SM0500', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-15', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'SM0600', 'Y', 'Y', 'Y', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-05-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000003', 'VD0201', 'Y', 'Y', 'N', '', '', 'N', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-01', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', '1111111', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', '5', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-10', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'AL0201', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', NULL, NULL, NULL, '', 'Y', '', '', '', '', '', '2021-09-16', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'AL0202', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-09-30', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'AL0301', 'Y', 'Y', 'Y', '', '', 'Y', NULL, NULL, NULL, '', 'Y', '', '', '', '', '', '2021-06-24', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'AL0304', 'Y', 'Y', 'Y', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-25', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'SI0101', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2021-05-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'SI0200', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-02', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'SI0401', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-08', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'SI0402', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-14', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'SI0501', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-15', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'SI0502', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '', '2021-06-18', 'system');

INSERT INTO sbrt.BMS_PROG_AUTH_INFO
  (AUTH_CD, PROG_CD, AUTH_CHECK, SCH_AH, SAV_AH, GEX_AH, IEX_AH, EXL_AH, DEL_AH, FN1_AH, FN2_AH, FN3_AH, FN4_AH, FN5_AH, FN6_AH, FN7_AH, FN8_AH, HELP_AH, UPD_DTM, UPD_ID)
VALUES
  ('AG00000004', 'SM0110', 'Y', 'Y', 'Y', 'N', 'N', 'N', NULL, NULL, NULL, 'N', 'N', 'N', 'N', 'N', 'N', 'Y', '2021-06-02', 'system');

