INSERT INTO sbrt.PLF_PLF_MAIN_MST
  (PLF_ID, INST_DT, IP, CITY, LANG_CD, TIME_ZONE, DATETIME_FORMAT, DATE_FORMAT, TIME_FORMAT, LOG_CD)
VALUES
  ('SB-2021-01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

