INSERT INTO sbrt.PLF_PLF_CH_MST
  (PLF_ID, CH_NM, CH_PORT, R_TIMEOUT, W_TIMEOUT, HEADER_TYPE, STR_TYPE, ENDIAN_TYPE, PRTL_VER, INDICATOR, MAX_SIZE, MAX_CNT, APDU_OFFSET, OPT_RC, OPT_TO, OPT_TR, OPT_CE, OPT_RF, OPT_LF)
VALUES
  ('SB-2021-01', 'COMMUNICATION-CHANNEL', '8083', 0, 0, 'A', 'EUC-KR', 'little', '1', 65, 65535, 256, 6, 3, 3, 0, 1, 0, 0);

