INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0000977', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0000978', '세종70자1502', 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0000979', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0000980', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0001590', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0001591', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0001592', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0001593', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0001618', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0001619', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0001620', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0001625', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010000', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010001', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010002', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010003', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010004', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010005', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010006', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010007', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010008', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('IMP0010009', NULL, 'IMP_000000', NULL, NULL, NULL, NULL, NULL, 'Y', NULL);

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('TRF0000001', NULL, 'TRF_000000', NULL, NULL, NULL, NULL, NULL, 'Y', '더로드신호시스템');

INSERT INTO sbrt.PLF_IMP_DEV_MST
  (IMP_ID, IMP_NM, IMP_TYPE, OWN_COMP_NM, COMP_ID, COMP_NM, VHC_ID, VHC_NO, USE_YN, REMARK)
VALUES
  ('TRF0000002', NULL, 'TRF_000000', NULL, NULL, NULL, NULL, NULL, 'Y', '테스트용');

