INSERT INTO sbrt.PLF_PLF_SVC_MST
  (PLF_ID, SVC_ID, SVC_NM, VER, ATTR, SVC_STS, ST_DTM, ED_DTM, CPU_USAGE, RAM_USAGE, HDD_USAGE, JVM_USAGE, REMARK, USE_YN)
VALUES
  ('SB-2021-01', 'T-CMM-01', 'T-COMMON', '1.0.0', 'kr.tracom.platform.attribute.common', NULL, '2021-05-12', '9999-12-31', NULL, NULL, NULL, NULL, NULL, 'Y');

INSERT INTO sbrt.PLF_PLF_SVC_MST
  (PLF_ID, SVC_ID, SVC_NM, VER, ATTR, SVC_STS, ST_DTM, ED_DTM, CPU_USAGE, RAM_USAGE, HDD_USAGE, JVM_USAGE, REMARK, USE_YN)
VALUES
  ('SB-2021-01', 'TA-BIS-01', 'T-BIS', '1.0.0', 'kr.tracom.platform.attribute.bis', NULL, '2021-05-12', '9999-12-31', NULL, NULL, NULL, NULL, NULL, 'Y');

INSERT INTO sbrt.PLF_PLF_SVC_MST
  (PLF_ID, SVC_ID, SVC_NM, VER, ATTR, SVC_STS, ST_DTM, ED_DTM, CPU_USAGE, RAM_USAGE, HDD_USAGE, JVM_USAGE, REMARK, USE_YN)
VALUES
  ('SB-2021-01', 'TA-BRT-01', 'T-BRT', '1.0.0', 'kr.tracom.platform.attribute.brt', NULL, '2021-05-12', '9999-12-31', NULL, NULL, NULL, NULL, NULL, 'Y');

INSERT INTO sbrt.PLF_PLF_SVC_MST
  (PLF_ID, SVC_ID, SVC_NM, VER, ATTR, SVC_STS, ST_DTM, ED_DTM, CPU_USAGE, RAM_USAGE, HDD_USAGE, JVM_USAGE, REMARK, USE_YN)
VALUES
  ('SB-2021-01', 'TA-IMP-01', 'T-IMP', '1.0.0', 'kr.tracom.platform.attribute.imp', NULL, '2021-05-12', '9999-12-31', NULL, NULL, NULL, NULL, NULL, 'Y');

