INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0000977', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, '2021-10-27', '2021-10-27');

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0000978', '¼¼Á¾70ÀÚ1502', '-', 'IMP_000000', 0, 0, 0, NULL, '2021-10-27', NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0000979', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0000980', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0001590', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0001591', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0001592', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0001593', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0001618', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0001619', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0001620', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0001625', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010000', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010001', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010002', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010003', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010004', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010005', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010006', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010007', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010008', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'IMP0010009', NULL, '-', 'IMP_000000', 0, 0, 0, NULL, NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'TRF0000001', NULL, '118.36.24.202:34122', 'TRF_000000', 0, 0, 0, '2021-10-29', NULL, NULL);

INSERT INTO sbrt.PLF_IMP_SESS_INFO
  (PLF_ID, SESS_ID, SESS_NM, SESS_IP, REMOTE_TYPE, ELAPSED_TIME, IN_PACKET, OUT_PACKET, LOGIN_DTM, LOGOUT_DTM, LAST_DTM)
VALUES
  ('SB-2021-01', 'TRF0000002', NULL, '-', 'TRF_000000', 0, 0, 0, NULL, NULL, NULL);

